Wait for onSdkReady callback to call isVerified
NexeraProtocol/nexeraid-examples pull request #180
Opened 2023-10-17 14:43 UTC by joelamouche

**JIRA task url** (if applicable)
https://allianceblockprotocol.atlassian.net/browse/NEXID-1732

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- wait for onSdkReady to call isWhitelisted
- button is in loading status in the meantime
- isWhitelisted is not called in the begining

**How to reproduce fix / test this PR?**

2023-10-19 16:35 UTC, LizanLycan reviewed
Just a little bit comments

2023-10-19 16:35 UTC, LizanLycan commented on aave_interface/src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
> +                <Trans>Loading Whitelist...</Trans>
I think that we could add this loading state to the `disabled` logic of the button

2023-10-19 16:35 UTC, LizanLycan commented on aave_interface/src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
> +              <Trans>Loading Whitelist...</Trans>
I think that we could add this loading state to the `disabled` logic of the button

2023-10-19 16:35 UTC, LizanLycan commented on aave_interface/src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx
> +              <Trans>Loading Whitelist...</Trans>
I think that we could add this loading state to the `disabled` logic of the button

2023-10-20 08:44 UTC, joelamouche commented on aave_interface/src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
> +                <Trans>Loading Whitelist...</Trans>
yes good call!
I added it

2023-10-20 13:22 UTC, LizanLycan requested changes

2023-10-20 13:22 UTC, LizanLycan commented on aave_interface/src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx
> +          {SupplyButton({
Ok... I understand the intention, but it's a React component, please call it as a React component:
`<SupplyButton disableSupply={disableSupply} ... />`

2023-10-20 13:22 UTC, LizanLycan commented on aave_interface/src/modules/dashboard/lists/SupplyButton.tsx
> +export const SupplyButton = (inputs: SupplyButtonInputs) => (
Generally for a React Component we call the `inputs` `props`

2023-10-20 13:34 UTC, joelamouche commented on aave_interface/src/modules/dashboard/lists/SupplyButton.tsx
> +export const SupplyButton = (inputs: SupplyButtonInputs) => (
Good point, corrected

2023-10-23 02:16 UTC, LizanLycan approved these changes
LGTM

2023-10-23 02:19 UTC, merged