NEXERAID-1546 - Updated handling from Identity SDK
NexeraProtocol/nexeraid-examples pull request #96
Opened 2023-09-21 13:39 UTC by LizanLycan

**JIRA task url** (if applicable)
https://allianceblockprotocol.atlassian.net/browse/NEXID-1546

**(If Bug) What was the problem being solved?**

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

**How to reproduce fix / test this PR?**

2023-09-21 15:31 UTC, joelamouche requested changes
This is good but I want you to go a little bit further in identity sdk integration and add the init flow in order to prepare for when the identity sdk needs to know the verifier address

2023-09-21 15:31 UTC, joelamouche commented on aave_interface/src/libs/IdentityClient.tsx
> +export const IDENTITY_CLIENT = new IdentityClient();
please also add
IDENTITY_CLIENT.init({
accessToken: kycAuth.accessToken,
signature: kycAuth.signature,
signingMessage: kycAuth.signingMessage,
})
with the logic to fetch the access token
this will be needed for the identity-sdk to know the address of verifier when it is not whiteliste

2023-09-22 08:57 UTC, joelamouche requested changes
When I test it I am not asked to sign a message 🤔 
ALso I have this error in my console: 
<img width="376" alt="Screenshot 2023-09-22 at 10 57 38" src="https://github.com/NexeraProtocol/nexeraid-examples/assets/16758383/81feb968-e476-49e9-8d74-fd343cc92196">

2023-09-25 02:54 UTC, LizanLycan commented
@joelamouche I already add the `init` logic, but not the `verify` because IDK how we going to manage the theme of the whitelisted after authenticate process.

2023-09-25 10:33 UTC, joelamouche requested changes
>I already add the init logic, but not the verify because IDK how we going to manage the theme of the whitelisted after authenticate process.

Yes that's good, we will take care of that later

I am still not being asked to sign a message though, and I am still getting that error in console:

<img width="361" alt="Screenshot 2023-09-25 at 12 32 25" src="https://github.com/NexeraProtocol/nexeraid-examples/assets/16758383/2386512a-c585-4656-9cb9-aed3bc0f538a">

We can get on a call to review this together if you want

2023-09-26 08:47 UTC, joelamouche approved these changes
Nice :)

2023-09-26 08:48 UTC, merged